language: java
sudo: false # faster builds
before_install:
 - pip install --user codecov
after_sucess:
 - bash <(curl -s https://codecov.io/bash)
jdk:
 - oraclejdk8
script: "mvn cobertura:cobertura"
token: dd2273e9-0930-4678-b792-19906907e7c8
