#
# This codecov.yml is the configuration for github.com/JulianoR/simple-jsf-morphia-mdl
# Codecov docs: https://docs.codecov.io/docs/codecov-yaml
# 
codecov:
  branch: master  # override the default branch

  notify:
    require_ci_to_pass: yes   # yes: will delay sending notifications until all ci is finished
    countdown: 2           # number of seconds to wait before first ci build check
    delay: 5               # number of seconds to wait between ci build checks
 
coverage:
  precision: 5  # 2 = xx.xx%, 0 = xx%
  round: up # default down
  range: "50...100"

  status:
    # Learn more at https://codecov.io/docs#yaml_default_commit_status
    project: true
    patch: true
    changes: false
token: dd2273e9-0930-4678-b792-19906907e7c8
comment:
  layout: "header, diff"
  behavior: default  # update if exists else create new
 
